# Generated by Django 3.0.7 on 2020-06-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='cnpj_vendor',
            field=models.CharField(max_length=25),
        ),
    ]
